/*
 * This file was generated by the Gradle 'init' task.
 */
import dependencies.ProjectConfig
import java.net.URI

plugins {
  kotlin("multiplatform")
}

repositories {
  mavenLocal()
  maven {
    url = uri("https://repo.maven.apache.org/maven2/")
  }

  maven {
    url = uri("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
  }
}

dependencies {
}

version = ProjectConfig.VERSION
group = ProjectConfig.GROUP


kotlin {
  jvm {
  }
  js {
  }
}



