/*
 * This file was generated by the Gradle 'init' task.
 */
import dependencies.ProjectConfig

plugins {
  kotlin("multiplatform")
}

repositories {
  mavenLocal()
  mavenCentral()

  maven {
    url = uri("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
  }
}

dependencies {
  commonMainImplementation("org.jetbrains.kotlin:kotlin-stdlib")
}

version = ProjectConfig.VERSION
group = ProjectConfig.GROUP


kotlin {
  jvm("jvm") {
  }
  js("js") {
    browser {}
    nodejs { }
  }
}



tasks {
  withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
      jvmTarget = "${JavaVersion.VERSION_17}"
    }
  }
}